# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Veitor的技术博客
subtitle: ''
description: '关注互联网技术，对Java、Golang、Kubernetes、AI应用、云原生架构等感兴趣'
keywords: 'php,CQRS,DDD,Event Sourcing,linux,Yii,kubernetes,golang,docker'
author: Veitor
language: zh-CN
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://www.veitor.net
root: /
permalink: posts/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing index.html from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :year/:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: prismjs
highlight:
  auto_detect: false
  line_number: true
  line_threshold: 0
prismjs:
  preprocess: false
  line_number: true
  line_threshold: 0

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

#关于主题的配置
theme_config:
  sidebar:
    offset: 12
  custom_file_path:
    variable: source/_data/variables.styl
    postBodyEnd: source/_data/post-body-end.njk
    bodyEnd: source/_data/body-end.njk
  codeblock:
    theme: 
      light: default
      dark: default
    prism:
      light: prism-tomorrow.min
      dark: prism-tomorrow.min
    copy_button:
      enable: true
#  custom_file_path:
#    postMeta: source/_data/post-meta.swig
  reading_progress:
    enable: true
  scheme: Pisces
  social:
    GitHub: https://github.com/veitor || fab fa-github
    #E-Mail: mailto:yourname@gmail.com || envelope
    Weibo: https://weibo.com/veitor || fab fa-weibo
    #Google: https://plus.google.com/yourname || google
    Twitter: https://twitter.com/Veitor_424 || fab fa-twitter
    #FB Page: https://www.facebook.com/yourname || facebook
    #StackOverflow: https://stackoverflow.com/yourname || stack-overflow
    #YouTube: https://youtube.com/yourname || youtube
    #Instagram: https://instagram.com/yourname || instagram
    #Skype: skype:yourname?call|chat || skype
    #RSS: /atom.xml || rss
  avatar:
    # Replace the default image and set the url here.
    url: /avatar.jpg
    # If true, the avatar will be dispalyed in circle.
    rounded: true
    # If true, the avatar will be rotated with the cursor.
    rotated: false
  menu:
    首页: / || fa fa-home
    归档: /archives/ || fa fa-archive
    标签: /tags/ || fa fa-tags
    分类: /categories/ || fa fa-th
    # 关于: /about/ || fa fa-user
#    招聘: /hire/ || fire
  footer:
    beian:
      enable: true
      icp:  苏ICP备14016154号-1
    since: 2019
    icon:
      name: fa fa-heart
      animated: true
      color: "#ff0000"
  favicon:
    small: /favicon.ico
    medium: /favicon.ico
  seo: true
  baidu_push: true
  baidu_analytics: "c422d42123239fdefb0180ed522d050a"
  fancybox: true
  lazyload: true
  pangu: true
  local_search:
    enable: true


# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: ''
