version: "3"
services:
  hexo:
    build: 
      context: .
      dockerfile: docker/local/Dockerfile
    ports:
      - 80:4000
    volumes:
      - ./themes:/home/themes
      - ./source:/home/source
      - ./_config.yml:/home/_config.yml
